name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any dependencies

      - name: Run tests (if applicable)
        run: |
          # Add test commands here if you have tests to run

      - name: Deploy to EC2
        run: |
          ssh -i /path/to/your/ec2/key.pem ec2-user@<YOUR_EC2_SERVER_IP> "cd /path/to/your/app && git pull && docker build -t my-app . && docker run -d -p 80:80 my-app"

